### ISSUE TITLE
No invoices are creating, only quotes

### ISSUE THREAD

**Issue by reff** [sliced-invoices/sliced-invoices-contact-form-7#1]
The following short codes create Quotes, so there's no way to create an Invoice
`[hidden sliced_quote_send "true"]`
`[hidden sliced_invoice_send "true"]`

Original ticket number #78799

**Comment by grantalltodavid** [comment]
Updated our documentation to talk about the `sliced_quote_or_invoice` field. See
https://github.com/sliced-invoices/sliced-invoices-contact-form-7/commit/3e13dc4f83b26e535d819c489907d577e0ea27f9
